- hosts: all
  become: yes
  vars:
    packages:
      - apache2
      - tree
      - unzip
    hello: world
  tasks: 
  - name: Install packages
    become: yes
    ansible.builtin.apt:
      name: '{{ packages }}'
      state: present
      update_cache: yes


  - name: Start service apache2, if not started
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes
  

  - name: Add the user tim
    ansible.builtin.user:
      name: "{{ item }}"
    loop:
      - tim
      - ann
      - bred


  # - name: Execute the command in remote shell
  #   ansible.builtin.shell: useradd tim
